version: "3.9"
services:
  bun-app:
    build: .
    ports:
      - "3002:3002"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: bun --hot src/index.tsx
    restart: unless-stopped
